kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wordpress-volumeclaim
  annotations:
    value: 'wow'
    cost-estimator.kpt.io/monthly-cost: '36.00'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 360Gi